name: CI

on:
    push:
        branches: [main, "feature/*"]
    pull_request:
        branches: [main]
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9.4.0

            - uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Install Playwright browsers
              run: pnpm exec playwright install --with-deps

            - name: Build server
              run: pnpm --filter server build

            #  server 的单测
            - name: Server unit tests
              run: pnpm --filter server test

            - name: Run E2E
              run: pnpm test:e2e

            - name: Upload Playwright report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
